spring:
  profiles:
    include: local, jwt, oauth

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 800MB

etc:
  base-url: ${BASE_URL}
  front-url: ${FRONT_URL}
  front-auth-success: ${FRONT_URL}/auth/success
  google-profile-url: https://www.googleapis.com/userinfo/v2/me
  kakao-profile-url: https://kapi.kakao.com/v2/user/me
  kakao-token-url: https://kauth.kakao.com/oauth/token
  kakao:
    client-id: ${KAKAO_CLIENT}
    redirect-uri: ${BASE_URL}/auth/v1/login/kakao

jwt:
  expiration:
    access: ${ACCESS_EXPIRATION}
    refresh: ${REFRESH_EXPIRATION}
  secret: ${JWT_SECRET}

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
        http-only: true
